mkdir -p ./start && printf -- "---\ntitle: getting started\n---\n\n" >>'./start/index.mdx'
mkdir -p ./you && printf -- "---\ntitle: is this for me?\n---\n\n" >>'./you/index.mdx'
mkdir -p ./langs && printf -- "---\ntitle: overview of languages\n---\n\n" >>'./langs/index.mdx'
mkdir -p ./js && printf -- "---\ntitle: javascript 101\n---\n\n" >>'./js/index.mdx'
mkdir -p ./react && printf -- "---\ntitle: react 101\n---\n\n" >>'./react/index.mdx'
mkdir -p ./python && printf -- "---\ntitle: python 101\n---\n\n" >>'./python/index.mdx'
mkdir -p ./devops && printf -- "---\ntitle: dev ops\n---\n\n" >>'./devops/index.mdx'
mkdir -p ./devsecops && printf -- "---\ntitle: dev sec ops\n---\n\n" >>'./devsecops/index.mdx'
mkdir -p ./gitops && printf -- "---\ntitle: git ops\n---\n\n" >>'./gitops/index.mdx'
mkdir -p ./febe && printf -- "---\ntitle: front end or back end?\n---\n\n" >>'./febe/index.mdx'
mkdir -p ./infosec && printf -- "---\ntitle: information security (infosec)\n---\n\n" >>'./infosec/index.mdx'
mkdir -p ./linux && printf -- "---\ntitle: linux\n---\n\n" >>'./linux/index.mdx'
mkdir -p ./cli && printf -- "---\ntitle: whats a command line??\n---\n\n" >>'./cli/index.mdx'
